version: "3.9"

services:
  app:
    image: ghcr.io/minato-stack/lxmd:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/lxmd:/root/.lxmd
      - ${APP_DATA_DIR}/reticulum:/root/.reticulum
