version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: tm-meshtastic-map_app_1
      APP_PORT: 8081
      PROXY_AUTH_ADD: "false"

  app:
    image: ghcr.io/liamcottle/meshtastic-map:latest
    restart: unless-stopped
