version: '3.9'
services:
  app_proxy:
    environment:
      APP_HOST: tm-nomadnet_app_1
      APP_PORT: 4001
      PROXY_AUTH_ADD: "false"
  app:
    image: ghcr.io/markqvist/nomadnet:master
    command: --daemon
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/nomadnet:/root/.nomadnetwork
      - ${APP_DATA_DIR}/reticulum:/root/.reticulum
