version: '3.9'
services:
  app_proxy:
    environment:
      APP_HOST: tm-meshtastic-web_app_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
  app:
    image: ghcr.io/meshtastic/web:latest
    restart: unless-stopped
