version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: tm-meshtxt_app_1
      APP_PORT: 8081
      PROXY_AUTH_ADD: "false"
  
  app:
    image: ghcr.io/minato-stack/meshtxt:latest
    restart: unless-stopped
