version: '3.9'

services:
  app_proxy:
    environment:
      APP_HOST: tm-meshcore-web_app_1
      APP_PORT: 8082
      PROXY_AUTH_ADD: "false"

  app:
    image: rgregg/meshcore-web:latest
    restart: unless-stopped
