version: '3.9'
services:
  app_proxy:
    environment:
      APP_HOST: tm-meshcore-web_app_1
      APP_PORT: 8082
      PROXY_AUTH_ADD: "false"
  app:
    image: ghcr.io/drewzh/meshcore-web-docker:latest
    restart: unless-stopped
    ports:
      - "8082:80"
